### ISSUE TITLE
Logs created with root permissions?

### ISSUE THREAD

**Issue by rcarmo** [piku/piku#150]
I'm trying to figure out if it's me or `piku-bootstrap` or a combination of both plus changes in `uwsgi`, but right now Ive hit an interesting issue while preparing tests:

```
rcarmo@monolith:~/OneDrive/Development/GitHub/sample-nodejs-app% git push piku master                       
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 4 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (13/13), 4.44 KiB | 4.44 MiB/s, done.
Total 13 (delta 0), reused 11 (delta 0)
remote: -----> Creating app 'sample_nodejs_app'
remote: -----> Deploying app 'sample_nodejs_app'
remote: HEAD is now at 8798232 imported from main repo
remote: -----> Node app detected.
remote: -----> Checking requirements: ['nodejs', 'npm']
remote: ['/usr/bin/nodejs', '/usr/bin/npm']
remote: -----> Creating node_modules for 'sample_nodejs_app'
remote: -----> Checking requirements: ['npm']
remote: ['/usr/bin/npm']
remote: -----> Running npm for 'sample_nodejs_app'
remote: npm WARN npm npm does not support Node.js v10.15.2
remote: npm WARN npm You should probably upgrade to a newer version of node as we
remote: npm WARN npm can't make any promises that npm will work with this version.
remote: npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
remote: npm WARN npm You can find the latest version at https://nodejs.org/
remote: npm notice created a lockfile as package-lock.json. You should commit this file.
remote: npm WARN piku-example@ No repository field.
remote: npm WARN piku-example@ No license field.
remote: 
remote: added 54 packages from 44 contributors in 16.35s
remote: -----> picking free port 40731
remote: -----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
remote: -----> nginx NGINX_IPV6_ADDRESS set to [::]
remote: -----> nginx BIND_ADDRESS set to 127.0.0.1
remote: -----> spawning 'sample_nodejs_app:web.1'
remote: -----> nginx will talk to the 'web' process via 127.0.0.1:40731
remote: -----> Releasing
remote: Hello!
remote: [ '/usr/bin/node',
remote:   '/home/piku/.piku/apps/sample_nodejs_app/hello.js' ]
remote: express exists
To quad.lan:sample_nodejs_app
 * [new branch]      master -> master
rcarmo@monolith:~/OneDrive/Development/GitHub/sample-nodejs-app% ssh piku@quad.lan logs sample_nodejs_app   
Traceback (most recent call last):
  File "/home/piku/piku.py", line 1385, in <module>
    piku()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/piku/piku.py", line 1166, in cmd_logs
    for line in multi_tail(app, logfiles):
  File "/home/piku/piku.py", line 968, in multi_tail
    files[f] = open(f)
PermissionError: [Errno 13] Permission denied: '/home/piku/.piku/logs/sample_nodejs_app/web.1.log'
rcarmo@monolith:~/OneDrive/Development/GitHub/sample-nodejs-app% 
```

somehow the log files are being created with UID `root`, which is just weird. I'm going to do a fresh install with only OS packages (just committed a `cloud-config` file for automating the install on Azure, which is easier for me) and test there, but if someone can reproduce this in the meantime...

**Comment by rcarmo** [comment]
Digging through this a bit more, somehow, and despite running `uwsgi` in emperor mode, the vassals are running as `root`, which is not consistent with older behaviour (`piku` was designed to run everything as the `piku` user to minimize security risks). I'm at a loss as to exactly what changes caused this to happen...
