### ISSUE TITLE
Issues with cloud-init process of installation

### ISSUE THREAD

**Issue by retrogradeorbit** [piku/piku#225]
I installed piku on 

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
# uname -a
Linux piku 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

following the cloud-init process https://github.com/piku/cloud-init/blob/master/baremetal-ubuntu/cloud-init.yml

I did not actually set this up *as* cloud init. I just initialised a ubuntu 20 instance and followed the steps contained inside the yaml file.

Tested with https://github.com/piku/sample-nodejs-app

```
git remote add piku piku@your_server:sample_nodejs_app
git push piku master
```

got: 

```
sample-nodejs-app$ git push piku master
Counting objects: 24, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (24/24), 6.40 KiB | 6.40 MiB/s, done.
Total 24 (delta 2), reused 23 (delta 2)
remote: -----> Creating app 'sample_nodejs_app'
remote: -----> Deploying app 'sample_nodejs_app'
remote: HEAD is now at 7efa857 Create dependabot.yml
remote: -----> Node app detected.
remote: -----> Checking requirements: ['nodejs', 'npm']
remote: [None, '/usr/bin/npm']
remote: -----> Checking requirements: ['node', 'npm']
remote: ['/usr/bin/node', '/usr/bin/npm']
remote: -----> Creating node_modules for 'sample_nodejs_app'
remote: -----> Checking requirements: ['nodeenv']
remote: [None]
remote: -----> Checking requirements: ['npm']
remote: ['/usr/bin/npm']
remote: -----> Running npm for 'sample_nodejs_app'
remote: npm WARN reify Removing non-directory /home/piku/.piku/apps/sample_nodejs_app/node_modules
remote: 
remote: added 54 packages, and audited 55 packages in 6s
remote: 
remote: 2 packages are looking for funding
remote:   run `npm fund` for details
remote: 
remote: found 0 vulnerabilities
remote: npm notice 
remote: npm notice New minor version of npm available! 8.1.2 -> 8.3.2
remote: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.2>
remote: npm notice Run `npm install -g npm@8.3.2` to update!
remote: npm notice 
remote: Traceback (most recent call last):
remote:   File "/home/piku/piku.py", line 1530, in <module>
remote:     cli()
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
remote:     return self.main(*args, **kwargs)
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
remote:     rv = self.invoke(ctx)
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
remote:     return _process_result(sub_ctx.command.invoke(sub_ctx))
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
remote:     return ctx.invoke(self.callback, **ctx.params)
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
remote:     return callback(*args, **kwargs)
remote:   File "/home/piku/piku.py", line 1445, in cmd_git_hook
remote:     do_deploy(app, newrev=newrev)
remote:   File "/home/piku/piku.py", line 364, in do_deploy
remote:     settings.update(deploy_node(app, deltas))
remote:   File "/home/piku/piku.py", line 584, in deploy_node
remote:     unlink(node_path_tmp)
remote: IsADirectoryError: [Errno 21] Is a directory: '/home/piku/.piku/apps/sample_nodejs_app/node_modules'
To your_server:sample_nodejs_app
 * [new branch]      master -> master
```

Found this error and a suggestion here https://github.com/piku/piku/issues/195#issuecomment-1013665468

shelled onto server and edited piku.py and changed line 584 to be:

```python
            import shutil
            shutil.rmtree(node_path_tmp)
```

ran the push again and just got:

```
$ git push piku master
Everything up-to-date
```

Seems the git push part worked first time, bought the repo up to date, and then the hook failed. Now the repo is up to date, so piku thinks everything is great rather than rerunning the post push hook and trying to setup the project again.

So tried a whole new piku app name:

```
$ git remote remove piku
$ git remote add piku piku@your_server:nodechat2
$ git push piku master
Counting objects: 24, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (24/24), 6.40 KiB | 6.40 MiB/s, done.
Total 24 (delta 2), reused 23 (delta 2)
remote: -----> Creating app 'nodechat2'
remote: -----> Deploying app 'nodechat2'
remote: HEAD is now at 7efa857 Create dependabot.yml
remote: -----> Node app detected.
remote: -----> Checking requirements: ['nodejs', 'npm']
remote: [None, '/usr/bin/npm']
remote: -----> Checking requirements: ['node', 'npm']
remote: ['/usr/bin/node', '/usr/bin/npm']
remote: -----> Creating node_modules for 'nodechat2'
remote: -----> Checking requirements: ['nodeenv']
remote: [None]
remote: -----> Checking requirements: ['npm']
remote: ['/usr/bin/npm']
remote: -----> Running npm for 'nodechat2'
remote: npm WARN reify Removing non-directory /home/piku/.piku/apps/nodechat2/node_modules
remote: 
remote: added 54 packages, and audited 55 packages in 1s
remote: 
remote: 2 packages are looking for funding
remote:   run `npm fund` for details
remote: 
remote: found 0 vulnerabilities
remote: -----> picking free port 49901
remote: -----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
remote: -----> nginx NGINX_IPV6_ADDRESS set to [::]
remote: -----> nginx BIND_ADDRESS set to 127.0.0.1
remote: -----> spawning 'nodechat2:web.1'
remote: -----> nginx will talk to the 'web' process via 127.0.0.1:49901
remote: -----> Releasing
remote: Hello!
remote: [ '/usr/bin/node', '/home/piku/.piku/apps/nodechat2/hello.js' ]
remote: node:internal/modules/cjs/loader:936
remote:   throw err;
remote:   ^
remote: 
remote: Error: Cannot find module 'express'
remote: Require stack:
remote: - /home/piku/.piku/apps/nodechat2/hello.js
remote:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
remote:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
remote:     at Module.require (node:internal/modules/cjs/loader:1005:19)
remote:     at require (node:internal/modules/cjs/helpers:102:18)
remote:     at Object.<anonymous> (/home/piku/.piku/apps/nodechat2/hello.js:5:13)
remote:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
remote:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
remote:     at Module.load (node:internal/modules/cjs/loader:981:32)
remote:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
remote:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
remote:   code: 'MODULE_NOT_FOUND',
remote:   requireStack: [ '/home/piku/.piku/apps/nodechat5/hello.js' ]
remote: }
remote: -----> Exiting due to release command error value: 1
To your_server:nodechat2
 * [new branch]      master -> master
```

presently stuck here.

**Comment by retrogradeorbit** [comment]
Blew away piku user and homedir and tried the bootstrap method in https://github.com/piku/piku-bootstrap

Installation went as planned. Now:

```
$ git remote remove piku
$ git remote add piku piku@your_server:nodechat
$ git push piku master
Counting objects: 24, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (24/24), 6.40 KiB | 6.40 MiB/s, done.
Total 24 (delta 2), reused 23 (delta 2)
remote: -----> Creating app 'nodechat'
remote: -----> Deploying app 'nodechat'
remote: HEAD is now at 7efa857 Create dependabot.yml
remote: -----> Node app detected.
remote: -----> Checking requirements: ['nodejs', 'npm']
remote: [None, '/usr/bin/npm']
remote: -----> Checking requirements: ['node', 'npm']
remote: ['/usr/bin/node', '/usr/bin/npm']
remote: -----> Creating node_modules for 'nodechat'
remote: -----> Checking requirements: ['nodeenv']
remote: ['/usr/bin/nodeenv']
remote: -----> Installing node version '14.17.6' using nodeenv
remote:  * Environment already exists: /home/piku/.piku/envs/nodechat
remote:  * Install node (14.17.6)... done.
remote: -----> Checking requirements: ['npm']
remote: ['/home/piku/.piku/envs/nodechat/bin/npm']
remote: -----> Running npm for 'nodechat'
remote: npm notice created a lockfile as package-lock.json. You should commit this file.
remote: npm WARN piku-example@ No repository field.
remote: npm WARN piku-example@ No license field.
remote: 
remote: added 54 packages from 44 contributors and audited 54 packages in 3.342s
remote: 
remote: 2 packages are looking for funding
remote:   run `npm fund` for details
remote: 
remote: found 0 vulnerabilities
remote: 
remote: -----> picking free port 45003
remote: -----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
remote: -----> nginx NGINX_IPV6_ADDRESS set to [::]
remote: -----> nginx BIND_ADDRESS set to 127.0.0.1
remote: -----> spawning 'nodechat:web.1'
remote: -----> nginx will talk to the 'web' process via 127.0.0.1:45003
remote: -----> Releasing
remote: Hello!
remote: [
remote:   '/home/piku/.piku/envs/nodechat/bin/node',
remote:   '/home/piku/.piku/apps/nodechat/hello.js'
remote: ]
remote: express exists
To your_server:nodechat
 * [new branch]      master -> master
```

```
$ ssh piku@your_server config:set nodechat NGINX_SERVER_NAME=your_server NGINX_HTTPS_ONLY=1
Setting NGINX_SERVER_NAME=your_server for 'nodechat'
Setting NGINX_HTTPS_ONLY=1 for 'nodechat'
-----> Deploying app 'nodechat'
-----> Node app detected.
-----> Checking requirements: ['nodejs', 'npm']
[None, '/usr/bin/npm']
-----> Checking requirements: ['node', 'npm']
['/usr/bin/node', '/usr/bin/npm']
-----> Checking requirements: ['nodeenv']
['/usr/bin/nodeenv']
-----> Node is installed at 14.17.6.
-----> Checking requirements: ['npm']
['/home/piku/.piku/envs/nodechat/bin/npm']
-----> picking free port 35995
-----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
-----> nginx NGINX_IPV6_ADDRESS set to [::]
-----> nginx BIND_ADDRESS set to 127.0.0.1
-----> nginx will look for app 'nodechat' on 127.0.0.1:35995
-----> writing temporary nginx conf
-----> getting letsencrypt certificate
[Tue Jan 25 14:00:00 AWST 2022] Create account key ok.
[Tue Jan 25 14:00:00 AWST 2022] Registering account
[Tue Jan 25 14:00:01 AWST 2022] Registered
[Tue Jan 25 14:00:01 AWST 2022] ACCOUNT_THUMBPRINT='...'
[Tue Jan 25 14:00:01 AWST 2022] Creating domain key
[Tue Jan 25 14:00:01 AWST 2022] The domain key is here: /home/piku/.acme.sh/your_server/your_server.key
[Tue Jan 25 14:00:01 AWST 2022] Single domain=your_server'
[Tue Jan 25 14:00:01 AWST 2022] Getting domain auth token for each domain
[Tue Jan 25 14:00:03 AWST 2022] Getting webroot for domain='your_server'
[Tue Jan 25 14:00:04 AWST 2022] Verifying: your_server
[Tue Jan 25 14:00:07 AWST 2022] Success
[Tue Jan 25 14:00:07 AWST 2022] Verify finished, start to sign.
[Tue Jan 25 14:00:07 AWST 2022] Lets finalize the order, Le_OrderFinalize: https://acme-v02.api.letsencrypt.org/acme/finalize/379323610/58249970930
[Tue Jan 25 14:00:09 AWST 2022] Download cert, Le_LinkCert: https://acme-v02.api.letsencrypt.org/acme/cert/0446f060205e669b8a47dc93e8355cf8274c
[Tue Jan 25 14:00:10 AWST 2022] Cert success.
-----BEGIN CERTIFICATE-----
MII...
-----END CERTIFICATE-----
[Tue Jan 25 14:00:10 AWST 2022] Your cert is in  /home/piku/.acme.sh/your_server/your_server.cer 
[Tue Jan 25 14:00:10 AWST 2022] Your cert key is in  /home/piku/.acme.sh/your_server/your_server.key 
[Tue Jan 25 14:00:10 AWST 2022] The intermediate CA cert is in  /home/piku/.acme.sh/your_server/ca.cer 
[Tue Jan 25 14:00:10 AWST 2022] And the full chain certs is there:  /home/piku/.acme.sh/your_server/fullchain.cer 
[Tue Jan 25 14:00:10 AWST 2022] Installing key to:/home/piku/.piku/nginx/nodechat.key
[Tue Jan 25 14:00:10 AWST 2022] Installing full chain to:/home/piku/.piku/nginx/nodechat.crt
-----> nginx will map app 'nodechat' to hostname(s) 'your_server'
-----> nginx will redirect all requests to hostname(s) 'your_server' to HTTPS
-----> Removing uwsgi configs to trigger auto-restart.
-----> spawning 'nodechat:web.1'
-----> nginx will talk to the 'web' process via 127.0.0.1:35995
-----> Releasing
Hello!
[
  '/home/piku/.piku/envs/nodechat/bin/node',
  '/home/piku/.piku/apps/nodechat/hello.js'
]
express exists
```

So seems to be an issue with the process in cloud-init?

**Comment by rcarmo** [comment]
Cloud-init is only for VM hosting where it is explicitly supported, and needs to be tweaked depending on host, so no surprises here…

**Comment by chr15m** [comment]
> tweaked depending on host

Can I modify the docs to reflect this? I think people are using the cloud-init examples verbatim thinking they will "just work". Maybe we should put the bootstrap script first in the recommended ways to install?

**Comment by rcarmo** [comment]
Well, they MUST work on the hosting providers they are designed for (that's why there are different files per folder), and are not really for bare metal installs unless they are tweaked.

(I honestly have no idea why people would think they are useful for local installs, but I'll read through things later and revise the wording on both repos...)

**Comment by rcarmo** [comment]
I've since added a set of more visible notes to the `cloud-init` repo, will move to the main `README` now.
