### ISSUE TITLE
IsADirectoryError on first nodejs deploy

### ISSUE THREAD

**Issue by chr15m** [piku/piku#228]
On #195 and on #225 they mentioned this bug with first time nodejs deploys. For some reason the second time you deploy it works (I guess because the directory exists already).

```
sample-nodejs-app$ git push piku master
Counting objects: 24, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (24/24), 6.40 KiB | 6.40 MiB/s, done.
Total 24 (delta 2), reused 23 (delta 2)
remote: -----> Creating app 'sample_nodejs_app'
remote: -----> Deploying app 'sample_nodejs_app'
remote: HEAD is now at 7efa857 Create dependabot.yml
remote: -----> Node app detected.
remote: -----> Checking requirements: ['nodejs', 'npm']
remote: [None, '/usr/bin/npm']
remote: -----> Checking requirements: ['node', 'npm']
remote: ['/usr/bin/node', '/usr/bin/npm']
remote: -----> Creating node_modules for 'sample_nodejs_app'
remote: -----> Checking requirements: ['nodeenv']
remote: [None]
remote: -----> Checking requirements: ['npm']
remote: ['/usr/bin/npm']
remote: -----> Running npm for 'sample_nodejs_app'
remote: npm WARN reify Removing non-directory /home/piku/.piku/apps/sample_nodejs_app/node_modules
remote: 
remote: added 54 packages, and audited 55 packages in 6s
remote: 
remote: 2 packages are looking for funding
remote:   run `npm fund` for details
remote: 
remote: found 0 vulnerabilities
remote: npm notice 
remote: npm notice New minor version of npm available! 8.1.2 -> 8.3.2
remote: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.2>
remote: npm notice Run `npm install -g npm@8.3.2` to update!
remote: npm notice 
remote: Traceback (most recent call last):
remote:   File "/home/piku/piku.py", line 1530, in <module>
remote:     cli()
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
remote:     return self.main(*args, **kwargs)
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
remote:     rv = self.invoke(ctx)
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
remote:     return _process_result(sub_ctx.command.invoke(sub_ctx))
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
remote:     return ctx.invoke(self.callback, **ctx.params)
remote:   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
remote:     return callback(*args, **kwargs)
remote:   File "/home/piku/piku.py", line 1445, in cmd_git_hook
remote:     do_deploy(app, newrev=newrev)
remote:   File "/home/piku/piku.py", line 364, in do_deploy
remote:     settings.update(deploy_node(app, deltas))
remote:   File "/home/piku/piku.py", line 584, in deploy_node
remote:     unlink(node_path_tmp)
remote: IsADirectoryError: [Errno 21] Is a directory: '/home/piku/.piku/apps/sample_nodejs_app/node_modules'
To your_server:sample_nodejs_app
 * [new branch]      master -> master
```

The fix should be this:

> Edit piku.py and changed line 584 to be:

```
            import shutil
            shutil.rmtree(node_path_tmp)
```

**Comment by chr15m** [comment]
Researching this some more, it looks like something changed in `npm` to start causing this (npm/cli#3669) however that appears to be a workaround because `npm install` was not respecting `NPM_CONFIG_PREFX` which I have filed a bug against in npm/cli/issues#4467. I am preparing a workaround for both issues and to try to normalize all of the `node_modules` path issues once and for all.

**Comment by chr15m** [comment]
This will also stop #159 from happening again since the fix (incoming) gets rid of the symlinked `node_modules` hack.

**Comment by chr15m** [comment]
Can reliably replicate this on node `16.14.0`. Have bumped the version in piku/sample-nodejs-app to use as a test case.

**Comment by chr15m** [comment]
@rcarmo I wonder if we should just install `node_modules` into the working directory. :thinking: Sometimes people (myself included) set their projects up to expect `node_modules` to be at the top level of their project and symlink to files in there etc. In this situation having it in `envs/APPNAME` is a bit counter intuitive. I have run into that issue before and I'm not sure the cleanest thing to do here.

Another option would be: 1. install into `envs/APPNAME/node_modules` but also 2. create a symlink in the apps directory by default and 3. have an option `NODE_NO_MODULES_SYMLINK` to remove the symlink if users don't want it.

**Comment by chr15m** [comment]
@asheroto this should be fixed already - did you see this bug recently?
