### ISSUE TITLE
Node.js Apps not configuring correctly on deploy

### ISSUE THREAD

**Issue by chalkers** [piku/piku#241]
Hey there,

I used the sample Node.js application's `Procfile` and `ENV` file and pushed it to my applicaiton and I get the following:

```sh
remote: -----> Deploying app 'test-node'
remote: HEAD is now at 5f38520 Procfile changes
remote: -----> Node app detected.
remote: -----> Checking requirements: ['nodejs', 'npm']
remote: [None, None]
remote: -----> Checking requirements: ['node', 'npm']
remote: [None, None]
remote: -----> Checking requirements: ['nodeenv']
remote: ['/usr/bin/nodeenv']
remote: -----> Checking requirements: ['nodeenv']
remote: ['/usr/bin/nodeenv']
remote: -----> Installing node version '16.14.0' using nodeenv
remote:  * Environment already exists: /home/piku/.piku/envs/test-node
remote:  * Install node (16.14.0Traceback (most recent call last):
remote:   File "/usr/bin/nodeenv", line 11, in <module>
remote:     load_entry_point('nodeenv==0.13.4', 'console_scripts', 'nodeenv')()
remote:   File "/usr/lib/python3/dist-packages/nodeenv.py", line 890, in main
remote:     create_environment(env_dir, opt)
remote:   File "/usr/lib/python3/dist-packages/nodeenv.py", line 731, in create_environment
remote:     install_node(env_dir, src_dir, opt)
remote:   File "/usr/lib/python3/dist-packages/nodeenv.py", line 594, in install_node
remote:     node_url = get_node_src_url(opt.node, get_node_src_url_postfix(opt)
remote:   File "/usr/lib/python3/dist-packages/nodeenv.py", line 503, in get_node_src_url_postfix
remote:     postfix_arch = arches[platform.machine()]
remote: KeyError: 'armv7l'
remote: -----> Checking requirements: ['npm']
remote: [None]
remote: -----> picking free port 40011
remote: -----> nginx NGINX_IPV4_ADDRESS set to 0.0.0.0
remote: -----> nginx NGINX_IPV6_ADDRESS set to [::]
remote: -----> nginx BIND_ADDRESS set to 127.0.0.1
remote: -----> Removing uwsgi configs to trigger auto-restart.
remote: -----> spawning 'test-node:web.1'
remote: -----> nginx will talk to the 'web' process via 127.0.0.1:40011
To jeeves.local:test-node
   1043919..5f38520  master -> master
```

And this is the following logs

```
➜  test-node git:(master) piku logs
Piku remote operator.
Server: piku@jeeves.local
App: test-node

web.1 | [uwsgi-daemons] respawning "./index.js 2>&1 | cat" (uid: 1001 gid: 33)
web.1 | /usr/bin/env: ‘node’: No such file or directory
web.1 | [uwsgi-daemons] throttling "./index.js 2>&1 | cat" for 1 seconds
web.1 | [uwsgi-daemons] respawning "./index.js 2>&1 | cat" (uid: 1001 gid: 33)
web.1 | /usr/bin/env: ‘node’: No such file or directory
web.1 | [uwsgi-daemons] throttling "./index.js 2>&1 | cat" for 1 seconds
web.1 | [uwsgi-daemons] respawning "./index.js 2>&1 | cat" (uid: 1001 gid: 33)
web.1 | /usr/bin/env: ‘node’: No such file or directory
web.1 | [uwsgi-daemons] throttling "./index.js 2>&1 | cat" for 2 seconds
web.1 | [uwsgi-daemons] respawning "./index.js 2>&1 | cat" (uid: 1001 gid: 33)
web.1 | /usr/bin/env: ‘node’: No such file or directory
web.1 | [uwsgi-daemons] throttling "./index.js 2>&1 | cat" for 2 seconds
web.1 | [uwsgi-daemons] respawning "./index.js 2>&1 | cat" (uid: 1001 gid: 33)
web.1 | /usr/bin/env: ‘node’: No such file or directory
web.1 | [uwsgi-daemons] throttling "./index.js 2>&1 | cat" for 3 seconds
web.1 | [uwsgi-daemons] respawning "./index.js 2>&1 | cat" (uid: 1001 gid: 33)
web.1 | /usr/bin/env: ‘node’: No such file or directory
web.1 | [uwsgi-daemons] respawning "./index.js 2>&1 | cat" (uid: 1001 gid: 33)
web.1 | /usr/bin/env: ‘node’: No such file or directory
web.1 | [uwsgi-daemons] throttling "./index.js 2>&1 | cat" for 7 seconds
^C%         
```

**Comment by chr15m** [comment]
Thanks for reporting this @chalkers. From what I can tell it looks like a nodeenv upstream issue. It seems like this version of nodeenv does not know about the `armv7l` platform:

```
remote:   File "/usr/lib/python3/dist-packages/nodeenv.py", line 503, in get_node_src_url_postfix
remote:     postfix_arch = arches[platform.machine()]
remote: KeyError: 'armv7l'
```

Although maybe it is because the OS version of nodeenv is out of date or something. :thinking:

What platform are you deploying on and what OS?

**Comment by chalkers** [comment]
`Raspberry Pi 2 Model B Rev 1.1`

`Linux version 5.15.32-v7+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1538 SMP Thu Mar 31 19:38:48 BST 2022`

I installed the default selection from Raspberry Pi's flashing tool.

I installed node via node source package and got it working but nodeenv isn't working.

**Comment by rcarmo** [comment]
Nodeenv will only work if you get the environment variables right - I don't use it myself since I stick to LTS from nodesource (and don't do all that much Node deployment), but @chr15m seems to be on the right track (in general, using non-system or non-nodesource packages on ARM is still a pain unless you're using ARM64...)
