### ISSUE TITLE
Piku not installing

### ISSUE THREAD

**Issue by erikgoldenstein** [piku/piku#245]
Hey,
Im new to the project so there is a real possibility that im in the wrong here.
I tried installing piku using the bootstrap method, everything worked until
`python3 piku.py setup` was executed.

It returned this error:
```python
Traceback (most recent call last):
  File "/home/piku/piku.py", line 1113, in <module>
    @piku.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'
```

Am I doing something wrong?
Using raspberry pi 3b with stock raspbian.

**Comment by rcarmo** [comment]
Hi there!

Can you tell us the following:

- Rasbpian version
- Python version
- output of `pip show click`

Thanks!

**Comment by erikgoldenstein** [comment]
Here you go
```bash
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux

pi@raspberrypi:~ $ python3 --version
Python 3.9.2

pi@raspberrypi:~ $ pip show click
Name: click
Version: 8.1.3
Summary: Composable command line interface toolkit
Home-page: https://palletsprojects.com/p/click/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/pi/.local/lib/python3.9/site-packages
Requires: 
Required-by: Flask

```

**Comment by rcarmo** [comment]
Hmmm. That is all recent versions, and a good match for the Ubuntu baseline. I see no obvious reason for the error, am going to try to reproduce it.

**Comment by rcarmo** [comment]
OK, I found it. You are, for some reason, not using the `click` version we test against (7.1.2):

```piku@piku-debian:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
piku@piku-debian:~$ uname -a
Linux piku-debian 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 13:14:54 UTC 2022 aarch64 GNU/Linux
piku@piku-debian:~$ python3 --version
Python 3.9.2
piku@piku-debian:~$  pip show click
Name: click
Version: 7.1.2
Summary: Composable command line interface toolkit
Home-page: https://palletsprojects.com/p/click/
Author: None
Author-email: None
License: BSD-3-Clause
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: 
piku@piku-debian:~$ pip install -U click
Requirement already satisfied: click in /usr/lib/python3/dist-packages (7.1.2)
Collecting click
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 6.0 MB/s 
Installing collected packages: click
Successfully installed click-8.1.3
piku@piku-debian:~$ pip show click
Name: click
Version: 8.1.3
Summary: Composable command line interface toolkit
Home-page: https://palletsprojects.com/p/click/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/piku/.local/lib/python3.9/site-packages
Requires: 
Required-by: 
piku@piku-debian:~$ python3 piku.py setup
Traceback (most recent call last):
  File "/home/piku/piku.py", line 1113, in <module>
    @piku.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'
piku@piku-debian:~$ 
```

@chr15m, is the bootstrap overwriting distro packages? I will need to check this.

**Comment by chr15m** [comment]
@rcarmo yep it's using the distro package. It installs `python3-click` using apt. Perhaps @erikgoldenstein installed his own `click` with `pip`? This could be related to #236.

**Comment by erikgoldenstein** [comment]
Hey, thanks a lot for the help!
I have been using Flask in the past and it has click 8.1.3 as a dependency so it was already installed before I tried getting piku to run.
I didn't install anything manually after performing the bootstrap script.

**Comment by rcarmo** [comment]
Well, the good news is that you can deploy your Flask app with any click version inside Piku, since it will be put into a virtualenv. But Piku right now is designed to be dropped onto an OS a python environment (to make it easier to install), and we’re constantly seesawing back and forth between distributions as they update their Python packages…
